### ISSUE TITLE
Avazu_x4 weirdly requires an extremely large amount of video memory.

### ISSUE THREAD

**Issue by Isuxiz** [reczoo/BARS#21]
I directly downloaded the preprocessed Avazu_x4 dataset, then discarded the id feature, and processed all other features as string categorical features. However, it is very strange that it needs a huge amount of GPU memory to be loaded (about 31G !!!!), and I can’t even use this dataset on Nvidia V100 32G because of OOM.
Is this normal? Is there any way to fix this?

**Comment by xpai** [comment]
We run the benchmark experiment on Avazu_x4 on 16G GPU. Can you provide more details? Which experiment steps do you follow?

**Comment by Isuxiz** [comment]
I use DeepFM implemented by FuxiCTR(2.0+), dataset is downloaded from link in [this section](https://github.com/openbenchmark/BARS/tree/main/datasets/Avazu#avazu_x4) and don't do any preprocess(nor did the preprocessing of x4_001 or x4_002 below).

my setting:
dataset_config.yaml
```yaml
Avazu:
  data_format: csv
  data_root: ../../../data/
  feature_cols:
    [
      {active: False, dtype: str, name: ["id"], type: categorical}
      {
        active: True,
        dtype: str,
        name:
          [
            "C1",
            "hour",
            "banner_pos",
            "site_id",
            "site_domain",
            "site_category",
            "app_id",
            "app_domain",
            "app_category",
            "device_id",
            "device_ip",
            "device_model",
            "device_type",
            "device_conn_type",
            "C14",
            "C15",
            "C16",
            "C17",
            "C18",
            "C19",
            "C20",
            "C21",
          ],
        type: categorical,
      },
    ]
  label_col: { dtype: int, name: "click" }
  min_categr_count: 1
  test_data: ../../../data/Avazu/test.csv
  train_data: ../../../data/Avazu/train.csv
  valid_data: ../../../data/Avazu/valid.csv
```
model_config.yaml
```yaml
DeepFM_Avazu:
  batch_norm: True
  batch_size: 4096
  dataset_id: Avazu
  early_stop_patience: 2
  embedding_dim: 32
  embedding_regularizer: 0.01
  epochs: 100
  hidden_activations: relu
  hidden_units: [400, 400, 400]
  learning_rate: 1.e-3
  loss: "binary_crossentropy"
  metrics: ["logloss", "AUC"]
  model: DeepFM
  monitor: AUC
  monitor_mode: max
  net_dropout: 0.3
  net_regularizer: 0
  optimizer: adam
  seed: 2023
  shuffle: True
  task: binary_classification
  verbose: 1
```
Another information that may be useful is that I found that the GPU memory usage are not significantly influenced by batch_size . I have tried training with `batch_size = 2`, but OOM errors still occur.
